on:
  pull_request:
    branches: [dev]
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Deps
        run: |
          sudo apt update
          sudo apt install zlib*

      - name: Checkout
        with:
          ref: dev
          path: base
        uses: actions/checkout@v2

      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: changes

      - id: dev_state_size
        run: |
          cd base
          make
          ./bin/filesize bin/filesize > out.md
          echo "::set-output name=size::$(cat out.md)"

      - id: current_state_size
        run: |
          cd changes
          make
          ./bin/filesize bin/filesize > out.md
          echo "::set-output name=size::$(cat out.md)"

      - uses: actions/github-script@v5
        with:
          script: |
            const message = `
            **Base**  

            \`\`\`
            ${{ steps.dev_state_size.outputs.size }}
            \`\`\`

            **PR**

            \`\`\`
            ${{ steps.current_state_size.outputs.size }}
            \`\`\`

            `;

            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: message
            })
